Social$orm/Controllers/WorksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Social_orm.Data;
using Social_orm.Models;

namespace Social_orm.Controllers
{
    public class WorksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WorksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Works
        public async Task<IActionResult> Index()
        {
            return View(await _context.works.ToListAsync());
        }

        // GET: Works/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.works
                .FirstOrDefaultAsync(m => m.Id == id);
            if (work == null)
            {
                return NotFound();
            }

            return View(work);
        }

        public IActionResult Check([Bind("BeneficiarID")] Work work)
        {
            //TempData["Person"] = "Child";
            string r = TempData.Peek("Person") as string;
            //TempData["Bid"] = work.BeneficiarID;
            ViewBag.result = r;
            return View();
        }

        

        [HttpPost]
        public IActionResult Work(string beneficiar, string wife , string child)
        {
            //int bid = (int)TempData["Bid"];
            //TempData.Keep();
            if (!string.IsNullOrEmpty(beneficiar))
            {
                if (beneficiar.Equals("Yes"))
                {
                    TempData["create"] = "yes";
                    return Redirect("~/Beneficiars/New/AddingInfo/Works");
                }
                else if (beneficiar.Equals("No"))
                    // return Redirect("~/Beneficiars/Create/" + bid + "/Addresses");
                    return Redirect("~/Beneficiars/New/AddingInfo/Addresses");

            }
            else if (!string.IsNullOrEmpty(wife))
            {
                if (wife.Equals("Yes"))
                {
                    TempData["create"] = "yes";
                    return Redirect("~/Beneficiars/New/AddingInfo/Wife/Works");
                }
                else if (wife.Equals("No"))
                    // return Redirect("~/Beneficiars/Create/" + bid + "/Children");
                    return Redirect("~/Beneficiars/New/AddingInfo/Children");

            }
            else if (!string.IsNullOrEmpty(child))
            {
                if (child.Equals("Yes"))
                {
                    TempData["create"] = "yes";
                    //return Redirect("~/Beneficiars/Create/" + bid + "/Child/Works/Create");
                    return Redirect("~/Beneficiars/New/AddingInfo/Child/Works");
                }
                else if (child.Equals("No"))
                    return Redirect("~/Beneficiars/New/AddingInfo/Children");

            }
            return null;
            //return View();
        }


        // GET: Works/Create
        public IActionResult Create()
        {
            string r = TempData.Peek("Person") as string;
            ViewBag.result = r;
            string c = TempData["create"] as string;
            ViewBag.create = c;

            string f = TempData.Peek("Field") as string;
            ViewBag.Field = f;
            string f2 = TempData.Peek("Field2") as string;
            ViewBag.Field = f2;

            ViewBag.Name = TempData.Peek("Name");
            return View();
        }

        // POST: Works/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("sector,TypeOfWork,Salary")] Work work)
        {
            if (ModelState.IsValid)
            {

                //int bid = (int)TempData["Bid"];
                string person = TempData.Peek("Person") as string;

                if (TempData["Field"] != null)
                {
                    work.BeneficiarID = (int)TempData.Peek("BenId");
                    _context.Add(work);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("ChooseField", "Home");
                }
                if (TempData["Field2"] != null)
                {
                    if (TempData.Peek("wid") != null) {
                        work.WifeID = (int)TempData["wid"];
                    }
                    else if(TempData.Peek("cid") != null)
                    {
                        work.ChildID = (int)TempData["cid"];
                    }
                    
                    _context.Add(work);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("ChooseField", "Home");
                }

                CreateModel model = TempData.Get<CreateModel>("model");
                string s = model.beneficiar.FirstName;
                

                if (person == "Wife")
                {
                    model.wife.work = work;
                    //TempData["model"] = model;
                    TempData.Put<CreateModel>("model", model);
                    return Redirect("~/Beneficiars/New/AddingInfo/Children");
                }

                if (person == "Child")
                {
                    //TempData["ChildWork"] = work;
                    //TempData["model"] = model;

                    model.children[model.children.Count - 1].work = work;
                    string t = model.children[model.children.Count - 1].work.TypeOfWork;
                    TempData.Put<CreateModel>("model", model);
                    return Redirect("~/Beneficiars/New/AddingInfo/Children");
                }

                //work.BeneficiarID = bid;
                //TempData["Work"] = work;

                model.work = work;
                string w = model.work.TypeOfWork;

                TempData.Put<CreateModel>("model", model);
                //TempData["model"] = model;

                int wi = model.work.Id;
                return Redirect("~/Beneficiars/New/AddingInfo/Addresses");
            }
            return View(work);
        }

        public IActionResult Cancel()
        {
            TempData["Field"] = null;
            TempData["Field2"] = null;
            return RedirectToAction("ChooseField", "Home");
        
        }

        public IActionResult Cancel2()
        {
            TempData["Name"] = null;
            return RedirectToAction("Index", "Beneficiars");
        }

        // GET: Works/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.works.FindAsync(id);
            if (work == null)
            {
                return NotFound();
            }
            ViewData["BeneficiarID"] = new SelectList(_context.Beneficiars, "Id", "FullName", work.BeneficiarID);
            ViewData["ChildID"] = new SelectList(_context.children, "Id", "Name", work.ChildID);
            ViewData["WifeID"] = new SelectList(_context.Wives, "Id", "FullName", work.WifeID);
            return View(work);
        }

        // POST: Works/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,sector,TypeOfWork,Salary,BeneficiarID,WifeID,ChildID")] Work work)
        {
            if (id != work.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(work);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkExists(work.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ChooseField", "Home");
                //return RedirectToAction(nameof(Index));
            }
            return View(work);
        }

        // GET: Works/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var work = await _context.works
                .FirstOrDefaultAsync(m => m.Id == id);
            if (work == null)
            {
                return NotFound();
            }

            return View(work);
        }

        // POST: Works/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var work = await _context.works.FindAsync(id);
            _context.works.Remove(work);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction("ChooseField", "Home");
        }

        private bool WorkExists(int id)
        {
            return _context.works.Any(e => e.Id == id);
        }
    }
}

Social$orm/Views/Home/ChildrenInfo.cshtml
@model IEnumerable<Social_orm.Models.Child>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Children Info";
}


<br>
<h2> All Children of @ViewBag.Name :</h2>
<br>

<div dir="rtl">
    <form method="post">
        <button class="bg-danger text-white" asp-action="NewChild" name="add" value="Children"> New Child </button>
    </form>
</div>

<br>
<br>
@{
    int i = 1;

    @foreach (var item in Model)
    {

        <br>
        <br>
        <table class="table">
            <thead>
                <tr class="bg-dark"> <th class="text-light" colspan="10"> Child @i</th> </tr>
            </thead>
            <thead>
                <tr class="bg-light">
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EducationLevel)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EducationalInstitute)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.yearlyCost)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.monthlyContribution)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Insured)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SocialStatus)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.HealthStatus)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.HandicapType)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EducationLevel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EducationalInstitute)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.yearlyCost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.monthlyContribution)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Insured)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SocialStatus)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HealthStatus)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HandicapType)
                    </td>

                    <td>
                        <a class="text-info" asp-controller="Children" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a class="text-info" asp-controller="Children" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
                @if (item.SocialStatus.Equals("Single"))
                {
                    @if (item.disease == null)
                    {

                        <tr>
                            <th colspan="5">No Disease </th>
                            <th colspan="5">
                                <form method="post">
                                    <button class="btn btn-info" asp-action="AddWD" name="ChildDisease" value="@item.Id"> Add it </button>
                                </form>
                            </th>
                        </tr>
                    }
                    else
                    {

                        <tr> <th class="text-dark" colspan="10"> Disease Info </th></tr>
                        <tr class="bg-light">
                            <th colspan="3">
                                @Html.DisplayNameFor(model => model.disease.DiseaseType)
                            </th>
                            <th colspan="3">
                                @Html.DisplayNameFor(model => model.disease.MedicineName)
                            </th>
                            <th colspan="3">
                                @Html.DisplayNameFor(model => model.disease.MedicineCost)
                            </th>
                            <th></th>
                        </tr>
                        <tr>
                            <td colspan="3">
                                @Html.DisplayFor(modelItem => item.disease.DiseaseType)
                            </td>
                            <td colspan="3">
                                @Html.DisplayFor(modelItem => item.disease.MedicineName)
                            </td>
                            <td colspan="3">
                                @Html.DisplayFor(modelItem => item.disease.MedicineCost)
                            </td>

                            <td>
                                <a class="text-info" asp-controller="Diseases" asp-action="Edit" asp-route-id="@item.disease.ID">Edit</a> |
                                <a class="text-info" asp-controller="Diseases" asp-action="Delete" asp-route-id="@item.disease.ID">Delete</a>
                            </td>
                        </tr>
                    }
                    @if (item.work == null)
                    {

                        <tr>
                            <th colspan="5">No Work </th>
                            <th colspan="5">
                                <form method="post">
                                    <button class="btn btn-info" asp-action="AddWD" name="ChildWork" value="@item.Id"> Add it </button>
                                </form>
                            </th>
                        </tr>
                    }
                    else
                    {
                        <tr> <th class="text-dark" colspan="10"> Work Info </th></tr>
                        <tr class="bg-light">
                            <th colspan="3">
                                @Html.DisplayNameFor(model => model.work.sector)
                            </th>
                            <th colspan="3">
                                @Html.DisplayNameFor(model => model.work.TypeOfWork)
                            </th>
                            <th colspan="3">
                                @Html.DisplayNameFor(model => model.work.Salary)
                            </th>
                            <th></th>
                        </tr>
                        <tr>
                            <td colspan="3">
                                @Html.DisplayFor(modelItem => item.work.sector)
                            </td>
                            <td colspan="3">
                                @Html.DisplayFor(modelItem => item.work.TypeOfWork)
                            </td>
                            <td colspan="3">
                                @Html.DisplayFor(modelItem => item.work.Salary)
                            </td>
                            <td>
                                <a class="text-info" asp-controller="Works" asp-action="Edit" asp-route-id="@item.work.Id">Edit</a> |
                                <a class="text-info" asp-controller="Works" asp-action="Delete" asp-route-id="@item.work.Id">Delete</a>
                            </td>
                        </tr>

                    }

                }
            </tbody>
        </table>
        <br>
        <br>
        i = i + 1;
    }
}

<br>
<br>
<hr>
<br>
<form method="post" asp-action="Back">
    <button class="btn btn-block bg-dark text-white"> Back </button>
</form>

Social$orm/Views/Home/ChooseBeneficiary.cshtml
@{
    ViewData["Title"] = "Find";
}

<h1>Select the Beneficiary's Fullname :</h1>

<hr />
<br>
<div class="row">
    <div class="col-md-4">
        <form asp-action="ChooseField">
            <div class="form-group">
                <select name="BeneficiarID" id="BeneficiarID" class="form-control" asp-items="ViewBag.BeneficiarID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Okay" class="btn btn-info" />
            </div>
        </form>
    </div>
</div>

Social$orm/Views/Home/ChooseField.cshtml
@{
    ViewData["Title"] = "Field";
}


<h3>Which field you want to edit in @ViewBag.Name 's Info :</h3>
<br>

<form asp-action="Edit">
    
    <div class="form-group text-center col-3">
        <button name="Field" id="Field" class="btn btn-block btn-primary" value="Beneficiars"> Personal Information </button><br><br>
        <button name="Field" id="Field" class="btn btn-block btn-secondary" value="Wives"> Wife's Information</button> <br><br>
        <button name="Field" id="Field" class="btn btn-block btn-danger" value="Children"> Children </button><br><br>
        <button name="Field" id="Field" class="btn btn-block btn-success" value="Diseases"> Disease </button><br><br>
        <button name="Field" id="Field" class="btn btn-info btn-block" value="Addresses"> Address </button><br><br>
        <button name="Field" id="Field" class="btn btn-warning btn-block" value="Loans"> Loan </button><br><br>
        <button name="Field" id="Field" class="btn btn-danger btn-block" value="Belongings"> Belongings</button> <br><br>
        <button name="Field" id="Field" class="btn btn-dark btn-block" value="Works"> Work </button><br><br>
        <button name="Field" id="Field" class="btn btn-info btn-block" value="SocialHelps"> Social Helps </button><br><br>
    </div>

    <hr>
    <button  class="btn btn-outline-dark text-dark" asp-action="Back2" > Back</button>

</form>

Social$orm/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<head>
    <style>
        body {
            background-image: url('/images/photo1.jpg');
            background-size: cover;
            background-color: white;
        }
    </style>
</head>


<form ... style="background: url('@Url.Content("~/images/photo1.jpg")');">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="text-center">
        <h1 style="font-family:'Arabic Typesetting';font-size:125px;color:Highlight;">جمعية رحماء </h1>

    </div>

</form>

@*<img src="C:\Users\HP-PC\source\repos\Social$Form - Copy\Social$orm\images\photo1.jpg" />
<img src="file:///C:/Users/HP-PC/source/repos/Social$Form%20-%20Copy/Social$orm/images/photo1.jpg" />*@





<style type="text/css">
    body {
        background-image: url('~/images/photo1.jpg');
    }
</style>

Social$orm/Views/Home/NotFound.cshtml
@{
    ViewData["Title"] = "NotFound";
}

<h3> The @ViewBag.Field Field of @ViewBag.Name was never submitted before .</h3>
<br>
<hr>

<div >
    <form method="post">
    <label > would you like to add it ?</label> 
    <button class="btn btn-info" asp-action="CreateField" name="add" value="@ViewBag.Field" > Add </button>
    <br><br><br>
            <label> If not get  </label>  <button class="btn btn-danger" asp-action="Back" name="add" value="Back" > Back </button>
        </form>
</div>

Social$orm/Views/Home/WifeInfo.cshtml
@model Social_orm.Models.Wife

@{
    ViewData["Title"] = "Wife Info";
}

<br>

<h2> @ViewBag.Name's Wife Information </h2>
<br><br>
<table class="table border-light">
    <thead>
        <tr class="bg-light">
            <th class="text-dark">
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th >
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlaceOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nationality)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.sect)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Insured)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HealthStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HandicapType)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody> 
        @* foreach hon *@
        
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.PlaceOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.Nationality)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.sect)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.Insured)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.HealthStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.HandicapType)
                </td>

                <td>
                    <a  asp-controller="Wives" asp-action="Edit" asp-route-id="@Model.Id">Edit</a> | <a asp-controller="Wives" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                </td>
            </tr>

            @if (@Model.work == null)
            {
                
                    <tr>
                        <th colspan="5">No Work </th>
                        <th colspan="5">
                            <form method="post">
                                <button class="btn btn-info" asp-action="AddWD" name="WifeWork" value="@Model.Id"> Add it </button>
                            </form>
                        </th>
                    </tr>
                
            }
            else
            {
                <tr> <th class="text-dark bg-light" colspan="10"> Her Work </th></tr>
                <tr>
                    <th colspan="3">
                        @Html.DisplayNameFor(model => model.work.sector)
                    </th>
                    <th colspan="3">
                        @Html.DisplayNameFor(model => model.work.TypeOfWork)
                    </th>
                    <th colspan="3">
                        @Html.DisplayNameFor(model => model.work.Salary)
                    </th>
                    <th></th>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.DisplayFor(modelItem => modelItem.work.sector)
                    </td>
                    <td colspan="3">
                        @Html.DisplayFor(modelItem => modelItem.work.TypeOfWork)
                    </td>
                    <td colspan="3">
                        @Html.DisplayFor(modelItem => modelItem.work.Salary)
                    </td>
                    <td>
                        <a asp-controller="Works" asp-action="Edit" asp-route-id="@Model.work.Id">Edit</a> | <a asp-controller="Works" asp-action="Delete" asp-route-id="@Model.work.Id">Delete</a>
                    </td>
                </tr>

            }

            @if (Model.disease == null)
            {
                
                    <tr>
                        <th colspan="5">No Disease </th>
                        <th colspan="5">
                            <form method="post">
                                <button class="btn btn-info" asp-action="AddWD" name="WifeDisease" value="@Model.Id"> Add it </button>
                            </form>
                        </th>
                    </tr>
                
            }
            else
            {
                <tr> <th class="text-dark bg-light" colspan="10"> Her Disease </th></tr>
                <tr>
                    <th colspan="3">
                        @Html.DisplayNameFor(model => model.disease.DiseaseType)
                    </th>
                    <th colspan="3">
                        @Html.DisplayNameFor(model => model.disease.MedicineName)
                    </th>
                    <th colspan="3">
                        @Html.DisplayNameFor(model => model.disease.MedicineCost)
                    </th>
                    <th></th>
                </tr>
                <tr>
                    <td colspan="3">
                        @Html.DisplayFor(modelItem => modelItem.disease.DiseaseType)
                    </td>
                    <td colspan="3">
                        @Html.DisplayFor(modelItem => modelItem.disease.MedicineName)
                    </td>
                    <td colspan="3">
                        @Html.DisplayFor(modelItem => modelItem.disease.MedicineCost)
                    </td>

                    <td>
                        <a asp-controller="Diseases" asp-action="Edit" asp-route-id="@Model.disease.ID">Edit</a> | <a asp-controller="Diseases" asp-action="Delete" asp-route-id="@Model.disease.ID">Delete</a>
                    </td>
                </tr>
            }
        
    </tbody>
</table>

<br>
<form method="post" asp-action="Back">
    <button class="btn btn-dark text-white" > Back </button>
</form>